---
title: "project proposal"
format: pdf
execute: 
  message: false
  warning: false
---

# 1. Set up

## Packages

```{r}
#| label: packages

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrap axis labels
library(scales)

# read .xlsx files
library(readxl)

# visualize missing data
library(naniar)

# arrange plots
library(patchwork)

```


## Data

```{r}
#| label: data

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects")


# read in site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# read in water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+")) 
```

# 2. Cleaning
## `sites` object
```{r}
#| label: ncos-site-object

# creating new object from sites
ncos_sites <- sites |> 
  # filter to only include NCOS sites sampled four times a year
  filter(sector == "NCOS" & sampling_frequency == "Quarterly")
```
## Cleaning `taxon_list`
```{r}
#| label: cleaning-taxon-list

# creating new clean object from taxon_list
taxon_list_clean <- taxon_list |> 
  # converting taxon name to snake case (no spaces or capital letters,
  # only underscores)
  mutate(verbatim_name = to_any_case(verbatim_name, case = "snake"))
```
## Cleaning `water_quality`
```{r}
#| label: water-quality-cleaning

# creating new clean object from water quality
water_quality_clean <- water_quality |> 
  # clean column names
  clean_names() |> 
  # filtering join: only include sites in ncos_sites
  semi_join(ncos_sites, by = "site") |> 
  # create new column to join with later data frames
  unite("date_site", date, site, remove = TRUE) |> 
  # group by date_site column
  group_by(date_site) |>
  # calculate median pH, salinity, DO
  summarize(med_ph = median(dissolved_oxygen_mg_l, na.rm = TRUE),
            med_sal = median(salinity_ppt, na.rm = TRUE),
            med_do = median(dissolved_oxygen_mg_l, na.rm = TRUE)) |> 
  # ungroup data frame
  ungroup() |> 
  # filter out salinity outliers
  filter(date_site != "2022-08-12_NVBR") 
```

## Cleaning `aq_ins`
```{r}
#| label: cleaning-aq-ins

# creating new clean object from aquatic inverts
aq_ins_clean <- aq_ins |> 
  # clean column names
  clean_names() |> 
  # filtering join: only include sites occurring in ncos_sites
  semi_join(ncos_sites, by = c("site")) |> 
  # renaming columns
  rename(date = date_on_vial) |> 
  # select columns of interest
  select(date, sample_type, site,
         ostracod,
         copepod,
         hemiptera_corixidae_boatman,
         cladocera,
         nematode,
         diptera_ceratopogonidae, 
         annelida_oligochaete,
         diptera_chironomid,
         annelida_polychaete) |> 
  # filter to only include "filtered beaker" samples
  filter(sample_type %in% c("FB 250", "FB250")) |> 
  # convert the data frame to long format
  pivot_longer(cols = ostracod:annelida_polychaete,
               names_to = "taxon",
               values_to = "abundance") |> 
  # group by date, site, taxon
  group_by(date, site, taxon) |> 
  # calculate average abundance per liter (sum abundance divided by 7.5 liters)
  summarize(ave_lit = sum(abundance, na.rm = TRUE)/7.5) |> 
  # ungroup data frame
  ungroup() |> 
  # create a new column called `date_site` to join with water quality
  unite("date_site", date, site, remove = FALSE) |> 
  # join with water quality
  left_join(water_quality_clean, by = c("date_site")) |> 
  # join with taxon list
  left_join(taxon_list_clean, by = c("taxon" = "verbatim_name")) |> 
  # add full names of sites
  mutate(site_full = case_when(
    site == "NVBR" ~ "North of Venoco Bridge",
    site == "NEC" ~ "South of Venoco Bridge",
    site == "NMC" ~ "Main Channel",
    site == "NPB" ~ "South of Phelps Bridge",
    site == "NPB1" ~ "North of Phelps Bridge",
    site == "NPB2" ~ "Phelps Road",
    site == "NWP" ~  "West Pond",
    site == "NDC" ~ "Devereux Creek"
  )) |> 
  # setting factor levels for site
  mutate(site_full = fct_reorder(site_full, med_do, .fun = "median", .na_rm = TRUE),
         site_full = fct_rev(site_full))
```

# Figure 1: Invertebrate abundance as a function of DO
```{r}
#| label: wrangle_data

# create object sal_taxa from aq_ins_clean
DO_taxa <- aq_ins_clean |> 
  # remove rows that are missing median salinity values
  filter(!is.na(med_do)) |> 
  # create column that calculates log-transformed abundance
  mutate(log_ave_lit = log(ave_lit + 1)) |>
  # mutates to title-case taxon names
  mutate(taxon = str_replace_all(taxon, "_", " "), taxon = str_to_title(taxon)) |>
  # order taxon levels by maximum average abundance per liter
  mutate(taxon = fct_reorder(taxon, ave_lit, .fun = max, .desc = TRUE)) |> 
  # keep only the columns needed for the figure
  select(date, site, site_full, taxon, ave_lit, log_ave_lit, med_do)
```

```{r}
#| label: DO_taxa_plot
#| fig-width: 10
#| fig-height: 8

# base layer: ggplot
DO_taxa_plot <- ggplot(data = DO_taxa, # assigns plot to object do_taxa_plot 
                        # uses sal_taxa data frame
                        mapping = aes(x = med_do, # x-axis: med_do
                                      y = log_ave_lit, # y-axis: log_ave_lit
                                      color = taxon)) + # color by taxon
  # first layer: points show individual abundance measurements 
  geom_point(shape = 16, # shape is circle
             size = 2, # size is 2
             alpha = 0.7) + # opacity is 0.7
  # separate panels for each taxon with free x- and y-axis scales
  facet_wrap(~ taxon, scales = "free") +
  # use non-default colors for points
  scale_color_viridis_d() +
  labs(x = "Median DO (mg/L)", # relabel x-axis
       y = "log + 1 transformed average abundance/L", # relabel y-axis
       # creates descriptive title
       title = "Invertebrate abundance as a function of DO") +
  # uses non-default theme
  theme_minimal() +
  # remove redundant legend
  theme(legend.position = "none")

# shows plot
DO_taxa_plot
```

# Figure 2: Variance of DO across sights
```{r}
# base layer
DO <- ggplot(data = aq_ins_clean,
       # x-axis: site
       # y-axis: mean salinity
       mapping = aes(x = site_full,
                     y = med_do)) +
  # first layer: salinity measurements at each survey
  geom_jitter(height = 0,
              width = 0.1,
              shape = 21) +
  # wrapping x-axis text
  scale_x_discrete(labels = label_wrap(width = 15)) +
  # second layer: points to represent means
  stat_summary(fun = median,
               color = "red",
               size = 1) +
  # relabelling x- and y-axes
  labs(x = "Site",
       y = "Median DO (mh/L)",
       title = "Site DO levels") +
  # different theme
  theme_bw()
# show plot
DO
```

# Figure 3: Aquatic Invert. Abundance Across Sites
```{r}
# creating new object from clean aquatic inverts 
abundance_by_site <- aq_ins_clean |> 
  # group by taxon, site
  group_by(taxon, site) |>
  # log + 1 transform mean abundance per liter
  mutate(log_ave_lit = log(ave_lit + 1)) 
```

```{r}
#| fig-width: 10
#| fig-height: 8
# base layer
abundance <- ggplot(data = abundance_by_site,
                   # x-axis: site
                   # y-axis: mean abundance/L
                   # color by taxon
                   mapping = aes(x = site_full,
                                 y = log_ave_lit, 
                                 color = taxon)) +
  # first layer: points to represent observations
  geom_point() +
  # second layer: points to represent medians
  #stat_summary(geom = "point",
               #fun = "median",
               #size = 4,
               #color = "blue") +
  # wrapping x-axis text
  scale_x_discrete(labels = label_wrap(15)) +
  # relabelling x- and y-axis, adding title
  labs(x = "Site",
       y = "log + 1 transformed average abundance/L",
       title = "Aquatic Invert. Abundance Across Sites") +
  # different theme
  theme_bw()

abundance
```
# Figure 4: Abundance over time

```{r}
#| label: invert-abundance-time
#| fig-width: 10
#| fig-height: 8

# create object for plotting abundance over time
abundance_time <- aq_ins_clean |> 
  # create log-transformed abundance column
  mutate(log_ave_lit = log(ave_lit + 1)) |> 
  # make taxon names easier to read
  mutate(taxon = str_replace_all(taxon, "_", " "),
         taxon = str_to_title(taxon)) |> 
  # order taxa by maximum abundance
  mutate(taxon = fct_reorder(taxon, ave_lit, .fun = max, .desc = TRUE)) |>
  filter(taxon %in% c("Ostracod", "Copepod", 'Cladocera', 
                      'Hemiptera Corixidae Boatman', 'Nematode'))

# base layer
abundance_time_plot <- ggplot(data = abundance_time,
                              # x-axis: sampling date
                              # y-axis: log-transformed abundance
                              # color by site
                              mapping = aes(x = date,
                                            y = log_ave_lit,
                                            color = site_full)) +
  # points show individual abundance measurements
  geom_point(size = 2,
             alpha = 0.7) +
  # lines connect observations through time by site and taxon
  geom_line(mapping = aes(group = site_full),
            alpha = 0.6) +
  # separate panels for each taxon
  facet_wrap(~ taxon, scales = "free_y") +
  # wrap site names in legend
  scale_color_viridis_d(labels = label_wrap(width = 20)) +
  # relabel axes and add title
  labs(x = "Date",
       y = "log + 1 transformed average abundance/L",
       color = "Site",
       title = "Invertebrate abundance over time") +
  # use clean theme
  theme_bw() +
  # angle x-axis labels so dates are readable
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))

# show plot
abundance_time_plot
```

